/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.beehyv.dsep.api;

import com.beehyv.dsep.model.OnSearchPost200Response;
import com.beehyv.dsep.model.OnSearchPostRequest;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-02-25T15:22:03.145011300+05:30[Asia/Calcutta]")
@Validated
@Tag(name = "on_search", description = "the on_search API")
@RequestMapping("${openapi.becknCore.base-path:}")
public interface OnSearchApi {

    default OnSearchApiDelegate getDelegate() {
        return new OnSearchApiDelegate() {};
    }

    /**
     * POST /on_search
     * Send catalog
     *
     * @param onSearchPostRequest TODO (optional)
     * @return Acknowledgement of message received (status code 200)
     */
    @Operation(
        operationId = "onSearchPost",
        tags = { "Beckn App Platform (BAP)", "Beckn Gateway (BG)" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Acknowledgement of message received", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = OnSearchPost200Response.class))
            })
        },
        security = {
            @SecurityRequirement(name = "GatewaySubscriberAuth"),
            @SecurityRequirement(name = "GatewaySubscriberAuthNew"),
            @SecurityRequirement(name = "SubscriberAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/on_search",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<OnSearchPost200Response> onSearchPost(
        @Parameter(name = "OnSearchPostRequest", description = "TODO") @Valid @RequestBody(required = false) OnSearchPostRequest onSearchPostRequest
    ) {
        return getDelegate().onSearchPost(onSearchPostRequest);
    }

}
